{
    "name": "Supricom Commissions",
    "version": "17.0.1.4.1",
    "summary": "Gestionar comisiones y metas de ventas",
    "description": """
        Este módulo permite gestionar tipos de vendedor para comisiones y metas mensuales de ventas.
        También extiende los contactos para incluir información del tipo de vendedor.
    """,
    "category": "Sales",
    "author": "LogicaCero for Marv1nG",
    "depends": ["base", "contacts", "sale", "account", "hr_contract", "base_setup"],
    "data": [
        "data/commission_vendor_type_data.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/res_users_views.xml",
        "security/commission_security.xml",
        "views/hr_contract_views.xml",
        "views/commission_vendor_type_views.xml",
        "views/commission_monthly_closing_views.xml",
        "views/commission_monthly_target_views.xml",
        "views/commission_matrix_views.xml",
        "views/commission_collection_matrix_views.xml",
        "views/commission_manager_volume_range_views.xml",
        "views/res_partner_views.xml",
        "views/product_template_views.xml",
        "views/product_pricelist_views.xml",
        "views/sale_order_views.xml",
        "views/commission_fixed_expense_views.xml",
        "views/account_move_views.xml",
        "views/commission_override_log_views.xml",
        "views/commission_settlement_views.xml",
        "wizard/commission_settlement_wizard_views.xml",
        "report/commission_report_action.xml",
        "report/commission_report_templates.xml",
        "report/commission_settlement_reports.xml",
        "report/commission_settlement_reports_templates.xml",
        "views/res_config_settings_views.xml",
        "views/res_company_views.xml",
        "views/account_untaxed_collection_report_views.xml",
        "views/commission_menus.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
