{
    "name": "Audit Log",
    "version": "17.0.1.0.0",
    "category": "Tools",
    "description": """The Audit Log Module will capture user actions (CRUD operations) on selected data models,
                providing a comprehensive record of key operations. """,
    "summary": """The Audit Log Odoo App is designed to meticulously track and log user actions, including Create,
                      Read, Update, and Delete (CRUD) operations across various data models. This module ensures transparency
                      and accountability, providing a comprehensive record of key operations to help maintain data integrity
                      within the Odoo system.""",
    "author": "Lógica Cero",
    "company": "Lógica Cero",
    "maintainer": "Lógica Cero",
    "contributor": "Lógica Cero",
    "website": "https://andresecas15.github.io/netflify/",
    "support": "logicacero.odoo@gmail.com",
    "depends": ["mail", "base", "account", "sale", "purchase", "stock", "analytic"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_seniat.xml",
        "data/ir_cron.xml",
        "data/auditlog_rules_data.xml",
        "views/auditlog_view.xml",
        "views/http_session_view.xml",
        "views/http_request_view.xml",
        "views/notification.xml",
        "views/client_error_view.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "auditlogs/static/src/js/client_error_handler.js",
        ],
    },
    "i18n": ["i18n/de.po", "i18n/es.po", "i18n/fr.po", "i18n/ja_JP.po"],
    "license": "OPL-1",
    "installable": True,
    "application": True,
    "auto_install": False,
    "price": 00.00,
    "currency": "USD",
    "post_init_hook": "post_init_setup_seniat_user",
}
